#####################################
############### Setup ###############
#####################################
stages:
  - unit_test

#####################################
############## Testing ##############
#####################################

unit_test_frontend:
  stage: unit_test
  image: node:latest
  before_script:
    - cd client
    - npm install
  script:
    - npm run test:coverage
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: ./client/coverage/clover.xml
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  tags:
    - dind

unit_test_backend:
  stage: unit_test
  image: python:3.9
  before_script:
    - pip install -r ./server/requirements.txt
  script:
    - coverage run -m pytest
  after_script:
    - coverage report
    - coverage xml -o coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: ./server/coverage.xml
  coverage: /TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  tags:
    - dind
